### ISSUE TITLE
Can't run the script, error 'No records found in handle'

### ISSUE THREAD

**Issue by Ptero64** [tobiashofmann88/snp_extraction_from_alignments#1]
Hello,

I try to run your script to get SNP alignments from phased MSA generated using PHYLUCE phased scripts. 
I tried to run it in a virtual conda environment including Cogent and Biopython. But I get the following error. Do you know what does it means  and how to fix it?

Sequences with missing data are not considered during SNP extraction (add flag --missing to command for higher SNP yield, including missing data)
Traceback (most recent call last):
  File "snps_from_uce_alignments.py", line 647, in <module>
    aln = AlignIO.read(open(output_file_fasta), "fasta", alphabet=Gapped(IUPAC.ambiguous_dna))
  File "/data/home/btx246/miniconda2/envs/Cogent/lib/python2.7/site-packages/Bio/AlignIO/__init__.py", line 439, in read
    raise ValueError("No records found in handle")
ValueError: No records found in handle

Thnaks you in advance for the help,

Best regards,
Nicolas

**Comment by tobiashofmann88** [comment]
@RominaSSBatista: Can you send me some of your alignments as an example (per email)? I'll have to run it myself to see what causes the error.

**Comment by tobiashofmann88** [comment]
Hi @leonvarhan, can you send me some of your alignments (e.g. via google drive, dropbox, etc) so I can trouble-shoot?

**Comment by tobiashofmann88** [comment]
@Ptero64, @RominaSSBatista, @leonvarhan:
I rewrote the code for the SNP extraction script and it should now be compatible with the newest python version and run much more smoothly. I wrote a detailed installation and usage tutorial, which you can find in the readme on the GitHub page. Please let me know in case you still run into problems.

**Comment by Muzammilpablo** [comment]
Hi!
While running a script Ima getting an error.


C:\Users\Muzammil Khan\Desktop\count>python count.py
Traceback (most recent call last):
  File "C:\Users\Muzammil Khan\Desktop\count\count.py", line 4, in <module>
    sequence = AlignIO.read("B16173.fasta", "fasta")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muzammil Khan\AppData\Roaming\Python\Python311\site-packages\Bio\AlignIO\__init__.py", line 385, in read
    raise ValueError("No records found in handle") from None
ValueError: No records found in handle.

Please help me to resolve it.
