### ISSUE TITLE
NameError: name 'temp_snp_align' is not defined

### ISSUE THREAD

**Issue by tvilhid** [tobiashofmann88/snp_extraction_from_alignments#2]
Hello Tobias,

I would like to extract SNPs from some phased selected loci. I am using the following commands:

python snp_extraction_from_alignments/bin/snps_from_uce_alignments.py --input ./processed/alignments/selected_loci_allele_alignments --config ./processed/alignments/configure_file_samples_selected_loci.txt --output ./processed/snps/empirical_data--extract_all --phased --delimiter _ --include_missing

I am getting the following error:
__________________________________________________
Processing file: ./processed/alignments/selected_loci_allele_alignments/gb/148.fasta
No SNP extraction performed for '148.fasta' due too a lack of polymorphic sites.
Traceback (most recent call last):
  File "snp_extraction_from_alignments/bin/snps_from_uce_alignments.py", line 199, in <module>
    for i in temp_snp_align.T:
NameError: name 'temp_snp_align' is not defined

However, the 148.fasta matrix have some SNPs in there.
Could you give me any idea about what might be wrong? Please, find attached the config file and the matrix.
Thank you,
Tamara

I just added ".txt" for uploading.
[148.fasta.txt](https://github.com/tobiashofmann88/snp_extraction_from_alignments/files/7562905/148.fasta.txt)
[configure_file_samples_selected_loci.txt](https://github.com/tobiashofmann88/snp_extraction_from_alignments/files/7562913/configure_file_samples_selected_loci.txt)

**Comment by tobiashofmann88** [comment]
I see that in your command there is a space missing in front of the --extract_all flag, does it work if yo fix that? The command should be:
```
python snp_extraction_from_alignments/bin/snps_from_uce_alignments.py --input ./processed/alignments/selected_loci_allele_alignments --config ./processed/alignments/configure_file_samples_selected_loci.txt --output ./processed/snps/empirical_data --extract_all --phased --delimiter _ --include_missing
```

**Comment by tobiashofmann88** [comment]
oh I see another issue now: the --input target has to be a directory, not an individual file. The script will be searching for fasta files in the target directory.

**Comment by tobiashofmann88** [comment]
And I see another potential issue: In your error message it seems like the fasta file is in the folder `processed/alignments/selected_loci_allele_alignments/gb/` but the input folder you provide to the script is `processed/alignments/selected_loci_allele_alignments/`. Make sure the target directory has no other contents or subfolders, except for your fasta files.

**Comment by tvilhid** [comment]
Hello Tobias, 

Thanks for your prompt response. 
Sorry, those errors are typos I have introduced accidentally when writing the message... 
I am still getting the same error. 

python snp_extraction_from_alignments/bin/snps_from_uce_alignments.py --input ./processed/alignments/selected_loci_allele_alignments/gb/ --config ./processed/alignments/configure_file_samples_selected_loci.txt --output ./processed/snps/empirical_data --extract_all --phased --delimiter _ --include_missing

Processing file: ./processed/alignments/selected_loci_allele_alignments/gb/148.gb.fasta
No SNP extraction performed for '148.gb.fasta' due too a lack of polymorphic sites.
Traceback (most recent call last):
  File "snp_extraction_from_alignments/bin/snps_from_uce_alignments.py", line 199, in <module>
    for i in temp_snp_align.T:
NameError: name 'temp_snp_align' is not defined

Thanks for helping!

**Comment by tobiashofmann88** [comment]
how many alignments do you have in your folder? or is it only this one?

**Comment by tandermann** [comment]
ah okay, I fixed it I think. The problem was that the script was not accepting lowercase DNA characters. It should work now (after you download the latest version of the script here from GitHub).

**Comment by tvilhid** [comment]
Yes! That was it! Thank you, Tobias!!
